// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuidkzhsbftzyxzroqbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aWRremhzYmZ0enl4enJvcWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzEzMDMsImV4cCI6MjA2MDMwNzMwM30.Umv4l-GZ7AVd6msBfWMsVTfzH0JyP4k2kkOelx_ZUDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);